spring:
  datasource:
    url: jdbc:mysql://localhost:3306/E_Commerce_Db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:1111/
     
server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/
    
