spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/E_Commerce_Db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8086

payment-service:
 keys:
  razorPayAPIKey: rzp_test_y3BlEFVYYriX8q
  razorPaySecretKey: tWqhPXJ6QYdieo3Lg8n9Kl6k